// mapmd.js — pure Markdown "full picture" builder (single source of truth for the
// export). Dual-runtime: a classic <script> on window.RV in the browser AND
// require()-able in Node. NO DOM, NO vendor deps — it only turns an AnalysisModel
// (from js/engine.js) into a deterministic Markdown string.
//
//   buildMarkdownMap(model, meta) -> string
//
// The browser glue (js/flowexport.js) and the Node CLI/HTTP API all call THIS — the
// Markdown/Mermaid generation is never duplicated.
(function (root, factory) {
	const api = factory();
	if (typeof module !== "undefined" && module.exports) module.exports = api; // Node (CommonJS)
	else Object.assign((root.RV = root.RV || {}), api); // browser → RV.buildMarkdownMap
})(typeof self !== "undefined" ? self : this, function () {
	"use strict";

	const MERMAID_NODE_CAP = 300; // keep the diagram renderable; full list stays in the table

	function baseName(path) {
		const i = path.lastIndexOf("/");
		return i === -1 ? path : path.slice(i + 1);
	}
	/** Path with the leading root segment dropped (for compact labels/links). */
	function relPath(path, root) {
		const prefix = root + "/";
		return path.startsWith(prefix) ? path.slice(prefix.length) : path;
	}
	function fmtBytes(n) {
		if (n == null || isNaN(n)) return "—";
		if (n < 1024) return `${n} B`;
		const units = ["KB", "MB", "GB", "TB"];
		let v = n / 1024, i = 0;
		while (v >= 1024 && i < units.length - 1) { v /= 1024; i++; }
		return `${v < 10 ? v.toFixed(1) : Math.round(v)} ${units[i]}`;
	}
	/** Escape pipes/newlines/backticks so a value is safe inside a Markdown table cell. */
	function cell(s) { return String(s).replace(/`/g, "'").replace(/\|/g, "\\|").replace(/\r?\n/g, " "); }
	/** Wrap a value as inline code, neutralising backticks/newlines that would break the span. */
	function code(s) { return "`" + String(s).replace(/[`\r\n]+/g, "'") + "`"; }

	// ---- Mermaid id sanitization -----------------------------------------
	// Mermaid node ids must match [A-Za-z0-9_]; build a stable, unique id per path.

	function makeIdFactory() {
		const used = new Set();
		const map = new Map();
		return function idFor(path) {
			if (map.has(path)) return map.get(path);
			let base = path.replace(/[^A-Za-z0-9_]/g, "_").replace(/^_+/, "") || "n";
			if (/^[0-9]/.test(base)) base = "n" + base;
			let id = base, k = 1;
			while (used.has(id)) id = `${base}_${k++}`;
			used.add(id);
			map.set(path, id);
			return id;
		};
	}
	/** Mermaid label text: drop chars (incl. newlines) that break the [".."] label syntax. */
	function label(s) { return String(s).replace(/[\r\n]+/g, " ").replace(/["`]/g, "'").replace(/[\[\]{}<>|]/g, " ").trim(); }

	// ---- the builder ------------------------------------------------------

	/**
	 * @param {object} model  AnalysisModel from engine.buildModel
	 * @param {object} [meta] { title?, generatedAt?, commands?:{engine,cli,http} }
	 */
	function buildMarkdownMap(model, meta) {
		meta = meta || {};
		const root = model.root || "repository";
		const generatedAt = meta.generatedAt || model.generatedAt || "";
		const title = meta.title || `Repository map — ${root}`;
		const m = model.metrics || {};
		const nodes = model.nodes || [];
		const byPath = new Map(nodes.map((n) => [n.path, n]));
		const out = [];

		// 1) Title + summary -------------------------------------------------
		out.push(`# ${title}`, "");
		out.push(
			`> Generated by the Repository Visualizer analysis engine.` +
			(generatedAt ? `  \n> **Generated:** ${generatedAt}` : "") +
			`  \n> **Root:** \`${root}\``,
			""
		);
		out.push(
			`This is the **authoritative architecture map**: a directed import/dependency flow ` +
			`from start to end. It indexes **${m.files}** analyzable files ` +
			`(**${m.codeFiles}** code) joined by **${m.edges}** import edges. ` +
			`**START** = ${m.entryCount} entry point(s); **END** = ${m.terminalCount} terminal module(s); ` +
			`${m.cycleCount} import cycle(s) detected across ${m.maxDepth} layered tier(s).` +
			(model.truncated ? `  \n\n> ⚠ Node list truncated to the analysis cap; counts reflect the analyzed subset.` : ""),
			""
		);

		// 2) Mermaid diagram -------------------------------------------------
		out.push(`## Architecture flow diagram`, "");
		out.push(buildMermaid(model, byPath), "");

		// 3) Entry points (START) -------------------------------------------
		out.push(`## Entry points (START)`, "");
		if (model.entries && model.entries.length) {
			for (const p of model.entries) {
				const n = byPath.get(p);
				const tag = n && n.seeded ? " · seeded" : "";
				out.push(`- ${code(relPath(p, root))}${tag}`);
			}
		} else out.push(`_No entry points detected._`);
		out.push("");

		// 4) Terminal modules (END) -----------------------------------------
		out.push(`## Terminal modules (END)`, "");
		if (model.terminals && model.terminals.length) {
			for (const p of model.terminals) out.push(`- ${code(relPath(p, root))}`);
		} else out.push(`_No terminal modules detected._`);
		out.push("");

		// 5) Cycles ----------------------------------------------------------
		out.push(`## Cycles`, "");
		if (model.cycles && model.cycles.length) {
			out.push(`Detected **${model.cycles.length}** import cycle(s) (strongly-connected components):`, "");
			model.cycles.forEach((c, i) => {
				out.push(`### Cycle ${i + 1}`);
				out.push(`- **Members:** ${c.members.map((p) => code(relPath(p, root))).join(" → ")}`);
				if (c.backEdges && c.backEdges.length) {
					out.push(`- **Back-edges (close the loop):**`);
					for (const be of c.backEdges) out.push(`  - ${code(relPath(be.from, root))} → ${code(relPath(be.to, root))}`);
				}
				out.push("");
			});
		} else out.push(`No cycles detected.`, "");

		// 6) Execution / dependency flow (START -> END) ----------------------
		out.push(`## Execution / dependency flow (START → END)`, "");
		if (model.layers && model.layers.length) {
			model.layers.forEach((bucket, i) => {
				const tier = i === 0 ? "Tier 0 · START" : i === model.layers.length - 1 ? `Tier ${i} · END` : `Tier ${i}`;
				out.push(`${i + 1}. **${tier}** (${bucket.length})`);
				for (const p of bucket) {
					const n = byPath.get(p);
					const role = n ? ` _(${n.role})_` : "";
					out.push(`   - ${code(relPath(p, root))}${role}`);
				}
			});
		} else out.push(`_No layered flow (no edges)._`);
		out.push("");

		// 7) Module inventory ------------------------------------------------
		out.push(`## Module inventory`, "");
		out.push(`| Path | Type | In | Out | Role | Size |`, `|------|------|---:|----:|------|-----:|`);
		for (const n of nodes) {
			out.push(`| \`${cell(relPath(n.path, root))}\` | ${n.type} | ${n.inDeg} | ${n.outDeg} | ${n.role} | ${fmtBytes(n.size)} |`);
		}
		out.push("");

		// 8) Metrics ---------------------------------------------------------
		out.push(`## Metrics`, "");
		out.push(`| Metric | Value |`, `|--------|------:|`);
		out.push(`| Files (analyzable) | ${m.files} |`);
		out.push(`| Code files | ${m.codeFiles} |`);
		out.push(`| Import edges | ${m.edges} |`);
		out.push(`| Entry points (START) | ${m.entryCount} |`);
		out.push(`| Terminal modules (END) | ${m.terminalCount} |`);
		out.push(`| Cycles | ${m.cycleCount} |`);
		out.push(`| Layered tiers (max depth) | ${m.maxDepth} |`);
		out.push(`| Orphans (no edges) | ${(model.orphans || []).length} |`);
		out.push("");

		return out.join("\n");
	}

	// ---- Mermaid flowchart generation ------------------------------------

	function buildMermaid(model, byPath) {
		const root = model.root || "repository";
		const idFor = makeIdFactory();
		const nodes = model.nodes || [];

		// Choose which nodes to render (cap for readability): prioritise entries,
		// cycle members, terminals, then highest-degree nodes.
		let render = nodes;
		let note = "";
		if (nodes.length > MERMAID_NODE_CAP) {
			const score = (n) => (n.entry ? 4 : 0) + (n.cycle ? 4 : 0) + (n.terminal ? 2 : 0) + (n.inDeg + n.outDeg) / 1000;
			render = nodes.slice().sort((a, b) => score(b) - score(a) || (a.path < b.path ? -1 : 1)).slice(0, MERMAID_NODE_CAP);
			note = `%% diagram truncated to ${MERMAID_NODE_CAP} of ${nodes.length} nodes — full list is in the Module inventory below`;
		}
		const renderSet = new Set(render.map((n) => n.path));

		// Group rendered nodes by their top-level folder (first segment after root).
		const groups = new Map(); // groupName -> [node]
		for (const n of render) {
			const rel = relPath(n.path, root);
			const slash = rel.indexOf("/");
			const g = slash === -1 ? "(root)" : rel.slice(0, slash);
			if (!groups.has(g)) groups.set(g, []);
			groups.get(g).push(n);
		}

		const lines = [];
		lines.push("```mermaid");
		lines.push("flowchart LR");
		if (note) lines.push("  " + note);
		lines.push("  classDef entry fill:#1f6feb,stroke:#fff,color:#fff;");
		lines.push("  classDef terminal fill:#2ea043,stroke:#fff,color:#fff;");
		lines.push("  classDef cycle fill:#e0556b,stroke:#fff,color:#fff;");

		// Subgraphs with node declarations.
		const groupNames = [...groups.keys()].sort();
		for (const g of groupNames) {
			const gid = idFor("__group__/" + g);
			lines.push(`  subgraph ${gid}["${label(g)}"]`);
			for (const n of groups.get(g).sort((a, b) => (a.path < b.path ? -1 : 1))) {
				const cls = n.role === "cycle" ? ":::cycle" : n.role === "entry" ? ":::entry" : n.role === "terminal" ? ":::terminal" : "";
				lines.push(`    ${idFor(n.path)}["${label(n.name)}"]${cls}`);
			}
			lines.push("  end");
		}

		// Links (only between rendered nodes). Cycle edges marked + dashed.
		for (const e of model.edges || []) {
			if (!renderSet.has(e.from) || !renderSet.has(e.to)) continue;
			const a = idFor(e.from), b = idFor(e.to);
			if (e.inCycle) lines.push(`  ${a} -. "cycle" .-> ${b}`);
			else lines.push(`  ${a} --> ${b}`);
		}

		lines.push("```");
		return lines.join("\n");
	}

	return { buildMarkdownMap };
});
